name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to Stellar Vision Team! Make sure to follow contribution guidelines."
        pr-message: "Congratulations on you first PR! Make sure to follow contribution guidelines"
